name: Telegram To WhatsApp

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Bot
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          META_TOKEN: ${{ secrets.META_TOKEN }}
          PHONE_ID: ${{ secrets.PHONE_ID }}
        run: python main.py
